### ISSUE TITLE
Apps not getting renamed

### ISSUE THREAD

**Issue by victor0d** [TBog/TBLauncher#236] opened 2022-01-23 17:42 UTC
Hi TBog,
I am not sure if I am being dumb in any way because it seems to me a very obvious bug and I had not seen any entry in the bug list.

Anyhow, it seems that I can't manage to rename an app.

I attach a short video and the interface settings.

In the video, "Firefox" is renamed to "Firefoxkkk", but it doesn't have any effect even after restarting the launcher.

Device: Oneplus6
OS: CRDroid6.23(Android10)
TBLauncher: 6.8

https://user-images.githubusercontent.com/90806717/150690843-63980809-8ce1-4ed5-8e57-0f50ddef2bec.mp4

[interface.xml.zip](https://github.com/TBog/TBLauncher/files/7921016/interface.xml.zip)

**Comment by TBog** [comment] 2022-01-23 18:17
On my device I can't reproduce it. I'll try the emulator.
When an app is renamed a toast should apper, if it does not then the operation failed.
If I can't reproduce it I'll make a debug build for you and  ask you for a logcat.

**Comment by victor0d** [comment] 2022-01-23 18:25
The toast doesn't appear. Then, as you say, it does fail.
I will test the debug build when ready.
Thanks.

**Comment by victor0d** [comment] 2022-01-23 19:10
Hi TBog,

I have (in the meantime) downgraded the version from v6.8 to v6.7:
- In this version, the apps get renamed as expected. I also get the toast when renaming.
- I had another bug (I hadn't log it yet): "Couldn't add a new search provider", although I could modify the existing entries successfully. In the version v6.7 it gets resolve too. I will not enter this bug until we see if we can sort it, because they seems linked in somehow to the latest version.
- The previous bug that I entered https://github.com/TBog/TBLauncher/issues/235 does NOT get resolved in the previous version

Cheers

**Comment by TBog** [comment] 2022-01-23 19:13
The issue has already been resolved in pre-release [v6.8-dev.1](https://github.com/TBog/TBLauncher/releases/tag/v6.8-dev.1)

**Closed** 2022-01-23 19:15 UTC
Labels: bug

**Comment by victor0d** [comment] 2022-01-23 19:44
Yes it is indeed working now. Thanks TBog.
