### ISSUE TITLE
Feature Request: Behavior - Dock

### ISSUE THREAD

**Issue by Saijin-Naib** [TBog/TBLauncher#420] opened 2023-09-28 15:22 UTC
**Description**
I really love how TinyBit allows almost all lists to be loaded both A-Z and Z-A sorted. 

One exception is tags pinned to the dock. They always open A-Z sorted. 

**Solution**
Add Dock section to Behavior, add item for sort order so we can choose A-Z or Z-A. 

**Alternative solutions**
Context menu item for tags in dock to change sort order for that individual tag item. 

**Additional context**
I thought I'd hate Z-A sorting when I first tried it in the default TinyBit config, but I'm actually really enjoying how little I have to reach for results most times now. Dock is the only exception.

**Comment by TBog** [comment] 2023-09-29 20:55
duplicate of #335

**Closed by TBog** 2023-09-29 20:55 UTC
