### ISSUE TITLE
7.4 - dev.1 crashes on Xiaomi Hyper OS for Poco

### ISSUE THREAD

**Issue by Xerolth** [TBog/TBLauncher#450] opened 2024-01-16 10:42 UTC
# Description #
Latest dev version of Tinybit crashes at startup and you can't do nothing, while 7.3 works fine (didn't try 7.4)

## Context ##
I installed 7.4 - dev.1 on my Poco F5 with Miui 14 (Android 13) and everything worked fine, but after updating to Hyper OS (Android 14) the launcher started crashing at startup and couldn't do anything except changing launcher. After that i reverted to 7.3 and everything works fine.

## Steps to Reproduce ##
To reproduce the behavior:
1. Install 7.4 - dev.1 on a device with Xiaomi Hyper OS
4. Popup message about Tinybit crashing appears

## Device info ##

  * Device: Poco F5
  * Model: 23049PCD8G
  * OS: Xiaomi Hyper OS (for Poco) 1.0.2.0.UMRMIXM - Android 14
  * TinyBit Launcher version: 7.4 - dev.1

**Comment by TBog** [comment] 2024-01-16 18:04
Could you provide a crash log?
I can't reproduce it on the emulator.

**Comment by Xerolth** [comment] 2024-01-17 23:58
[log.txt](https://github.com/TBog/TBLauncher/files/13970032/log.txt)

Here it is, I hope it helps.

**Comment by TBog** [comment] 2024-02-29 21:30
Should be fixed with commit https://github.com/TBog/TBLauncher/commit/3c60e394ef70b0a450b840d90ca466ca9a6f5a85
Check out [Update 7.4 - dev.2](https://github.com/TBog/TBLauncher/releases/tag/v7.4-dev.2)

**Closed by TBog** 2024-02-29 21:30 UTC
Labels: bug

**Comment by daffydock** [comment] 2024-04-21 11:43
For anyone who find this, mine too was crashing. Albeit it might not work for all, going into Apps, hitting the *gear* icon, going into settings and deleting the Icon Chache fixed it for me. 

No more crashing. TBL starts like it used to.
